### ISSUE TITLE
Autoware.universe traffic light recognition in carla 

### ISSUE THREAD

**Issue by liuypcoding** [hatem-darweesh/op_agent#1]
Hi , I'm trying use Autoware.universe traffic light recognition in carla . I hand download your vector map, but can't open it by autoware vector map tools:
[https://tools.tier4.jp/feature/vector_map_builder_ll2/](url)

![003](https://user-images.githubusercontent.com/46860249/188481717-8402cbd0-ad6b-4900-a528-07b96949c5c7.png)
but when I used JOSM opened the Town01.osm,but no found traffic light in vector map 
![004](https://user-images.githubusercontent.com/46860249/188482141-be0e36d2-5c11-42e8-bb12-f9387644de47.png)

And I alse note the op_agent include tlr and bosh traffic light name.
![005](https://user-images.githubusercontent.com/46860249/188482488-a972664d-46b7-4cb6-ac2b-a3d89daa36fb.png)

Can you gave me some advices about how can i use Autoware.universe traffic light recognition in carla,.

Best best wishes！Thank you!!

**Comment by hatem-darweesh** [comment]
@liuypcoding 
you can check these maps using [assuremappingtools ](https://github.com/hatem-darweesh/assuremappingtools). the problem is the coordinates system. These maps include UTM coordinates rather MGRS. 
In my test I publish the traffic light signal manual. If detecting the traffic light state can be done automatically using autoware.universe ?! 

About the op_tlr it works with autoware.ai and OpenPlanner 2.5. I didn't import these features to the ROS2 bridge yet.

**Comment by liuypcoding** [comment]
> 

Thank you feedback！
Detecting the traffic light state can be done automatically using autoware.universe . you can Check out this document：
[traffic_light_classifier](https://autowarefoundation.github.io/autoware.universe/main/perception/traffic_light_classifier/)

![0007](https://user-images.githubusercontent.com/46860249/188524354-4545366c-ae3b-448c-9b18-909493fbb79b.png)

When run the traffic light recognition, it's include all nodes and topic about traffic ,like this :
![008](https://user-images.githubusercontent.com/46860249/188524650-5671767b-6055-4581-8fa6-459e0d5c8b76.png)

Thanks

**Comment by liuypcoding** [comment]
> 

Thank you feedback！
Detecting the traffic light state can be done automatically using autoware.universe . you can Check out this document：
[https://autowarefoundation.github.io/autoware.universe/main/perception/traffic_light_classifier/](url)

![0007](https://user-images.githubusercontent.com/46860249/188524354-4545366c-ae3b-448c-9b18-909493fbb79b.png)

When run the traffic light recognition, it's include all nodes and topic about traffic ,like this :
![008](https://user-images.githubusercontent.com/46860249/188524650-5671767b-6055-4581-8fa6-459e0d5c8b76.png)

Thanks

**Comment by yuasabe** [comment]
@liuypcoding Hi, I was also trying to have Autoware.universe do traffic light recognition in Carla. 

Have you been able to do this after all? Do you have any updates?

Thanks in advance.

**Comment by liuypcoding** [comment]
> 

Calar don't had vector_map include traffic light  ,create and draw　HD map is hard for me .   But LGSVL Satisfied for me about autoware.universe do traffic light recognition with the simulation.

Now,  I'm trying testing with the traffic light recognition.
 Hope it's helpful .

**Comment by yuasabe** [comment]
@hatem-darweesh Do you by any chance have the lanelet2 files for the Carla Towns that includes the traffic light information? 
In your tutorial video (specifically here: https://youtu.be/dxwwNacez7o?t=1173), you are publishing the traffic light information to the traffic light ID 29715. I couldn't find this data anywhere in the provided Lanelet2 files.

Thanks in advance.

**Comment by gaokao123** [comment]
@hatem-darweesh  I also have the same question. 
1. In your tutorrial video,  you are publishing the traffic light information to the traffic light ID 29715, but I could not find this data in the Carla Towns, do you make any additional changes to the lanelet2 files?
2. In addition, The window of recognitionResultOnImage  in Rviz has no dynamic image, do you have any idea?
![image](https://user-images.githubusercontent.com/111047949/194815345-ed13c2ca-e280-418b-8796-93c2e4821eaf.png)

Thanks in advance

**Comment by hatem-darweesh** [comment]
In these examples I added the traffic light manually to the map for testing. 
only Town01 and Town02 include some traffic light information. 
Check latest maps from CARLA team, maybe they have added better traffic light representation. 

@gaokao123 you need to select the correct topic to be published. maybe it is not the default message name.

**Comment by gaokao123** [comment]
@hatem-darweesh Thank you feedback！
do you have the new HD map with traffic light? I couldn't find this data anywhere in the Lanelet2 files which you provided , create and draw HD map is hard for me. Thank you

**Comment by gaokao123** [comment]
@hatem-darweesh Thank you feedback!
I tried to add traffic light  to the map with the JOSM tool,but failed.  and the carla team did not updade the map either, do you have lanelet2 map with traffic light? Thank you!

**Comment by hatem-darweesh** [comment]
@gaokao123 
I had experimental one for Town01. 
check https://drive.google.com/drive/u/1/folders/1cQxiEteKMwZQZSHuotd4Bw1smzfOG67k

**Comment by gaokao123** [comment]
@hatem-darweesh 
ok，I have got the map for Town01, thank you very much!

**Comment by liuypcoding** [comment]
> @hatem-darweesh Thank you feedback! I tried to add traffic light to the map with the JOSM tool,but failed. and the carla team did not updade the map either, do you have lanelet2 map with traffic light? Thank you!
![019_1_台式机上运行结果](https://user-images.githubusercontent.com/46860249/199635628-5bb326b7-3f54-45ed-8ae6-78e41c131665.png)

If you only want recurrent the traffic light regconition , lgsvl  more convenient in osm and simulator than carla, help it's helpful. good luck!!

**Comment by liuypcoding** [comment]
> @gaokao123
 If you only want recurrent the traffic light regconition , lgsvl more convenient in osm and simulator than carla,  good lucky!

![result](https://user-images.githubusercontent.com/46860249/199636488-db9ea69d-069e-406c-b3a5-474bc207af34.png)

**Comment by gaokao123** [comment]
@liuypcoding 
ok，Thank you,  can you tell me which maps and vehicle to be choose in the store of lgsvl?

**Comment by liuypcoding** [comment]
@gaokao123 
SanFrancisco、shalun also ok, vehicle choose anyone .

**Comment by gaokao123** [comment]
@liuypcoding
ok, thank you for feedback, I will try, whether I need to configure sensors info myself and where can I get the Sensor Configurations of the vehicle?

**Comment by liuypcoding** [comment]
@gaokao123 
You need calculate the cam_info according  [https://github.com/lgsvl/simulator/issues/1524](url)；

What's more , you need other device to install foxy ,so have environment to install lgsvl_ros2_bridge. The [lgsvl tutorial](https://www.svlsimulator.com/docs/getting-started/getting-started/) show how to simulator with other device .
